// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB5khrEVZYcOILTPiuUSrYUyyNXskcacw',
    appId: '1:35123235879:web:e27323aa334083e5cc1202',
    messagingSenderId: '35123235879',
    projectId: 'instagram-clone-98007',
    authDomain: 'instagram-clone-98007.firebaseapp.com',
    storageBucket: 'instagram-clone-98007.appspot.com',
    measurementId: 'G-WTN14V4N6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3iNqiKosHi3hC_EXjwdtLZOcweofJH_c',
    appId: '1:35123235879:android:5baab9d1f2a6ff42cc1202',
    messagingSenderId: '35123235879',
    projectId: 'instagram-clone-98007',
    storageBucket: 'instagram-clone-98007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJmbQOdR5t3N7RDR_hFhSrBcDYXEJd50',
    appId: '1:35123235879:ios:5ae62c28a86eb16fcc1202',
    messagingSenderId: '35123235879',
    projectId: 'instagram-clone-98007',
    storageBucket: 'instagram-clone-98007.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
